# SPDX-License-Identifier: MIT
srcs-y += base.c
srcs-y += fan.c
srcs-y += fannil.c
srcs-y += fanpwm.c
srcs-y += fantog.c
srcs-y += ic.c
srcs-y += temp.c
srcs-y += nv40.c
srcs-y += nv50.c
srcs-y += g84.c
srcs-y += gt215.c
srcs-y += gf100.c
srcs-y += gf119.c
srcs-y += gk104.c
srcs-y += gm107.c
srcs-y += gm200.c
srcs-y += gp100.c
