
#ifndef VTACONFIG_H_
#define VTACONFIG_H_

#define VTA_LOG_INP_WIDTH 3
#define VTA_LOG_WGT_WIDTH 3
#define VTA_LOG_ACC_WIDTH 5
#define VTA_LOG_BATCH 0
#define VTA_LOG_BLOCK 4
#define VTA_LOG_UOP_BUFF_SIZE 15
#define VTA_LOG_INP_BUFF_SIZE 15
#define VTA_LOG_WGT_BUFF_SIZE 18
#define VTA_LOG_ACC_BUFF_SIZE 17

#define VTA_LOG_BLOCK_IN VTA_LOG_BLOCK
#define VTA_LOG_BLOCK_OUT VTA_LOG_BLOCK
#define VTA_LOG_OUT_WIDTH VTA_LOG_INP_WIDTH
#define VTA_LOG_OUT_BUFF_SIZE (VTA_LOG_ACC_BUFF_SIZE + VTA_LOG_OUT_WIDTH + VTA_LOG_ACC_WIDTH)

#endif