
all:
	@echo "/* Generated by $(src)/Makefile */";
	@echo "    .section .rodata"				;
	@echo "    .p2align 4"					;
	@echo "_fw_$(FWSTR)_bin:"				;
	@echo "    .incbin \"$(fwdir)/$(FWNAME)\""		;
	@echo "_fw_end:"						;
	@echo "    .section .rodata.str,\"aMS\",$(PROGBITS),1"	;
	@echo "    .p2align $(ASM_ALIGN)"			;
	@echo "_fw_$(FWSTR)_name:"				;
	@echo "    .string \"$(FWNAME)\""			;
	@echo "    .section .builtin_fw,\"a\",$(PROGBITS)"	;
	@echo "    .p2align $(ASM_ALIGN)"			;
	@echo "    $(ASM_WORD) _fw_$(FWSTR)_name"		;
	@echo "    $(ASM_WORD) _fw_$(FWSTR)_bin"			;
	@echo "    $(ASM_WORD) _fw_end - _fw_$(FWSTR)_bin"