# SPDX-License-Identifier: GPL-2.0
srcs-$(CONFIG_PCIE_MOBIVEIL) += pcie-mobiveil.c
srcs-$(CONFIG_PCIE_MOBIVEIL_HOST) += pcie-mobiveil-host.c
srcs-$(CONFIG_PCIE_MOBIVEIL_PLAT) += pcie-mobiveil-plat.c
srcs-$(CONFIG_PCIE_LAYERSCAPE_GEN4) += pcie-layerscape-gen4.c
