# SPDX-License-Identifier: MIT
srcs-y += falcon.c
srcs-y += xtensa.c

subdirs-y += bsp
subdirs-y += ce
subdirs-y += cipher
subdirs-y += device
subdirs-y += disp
subdirs-y += dma
subdirs-y += fifo
subdirs-y += gr
subdirs-y += mpeg
subdirs-y += msenc
subdirs-y += mspdec
subdirs-y += msppp
subdirs-y += msvld
subdirs-y += nvenc
subdirs-y += nvdec
subdirs-y += pm
subdirs-y += sec
subdirs-y += sec2
subdirs-y += sw
subdirs-y += vic
subdirs-y += vp
